### ISSUE TITLE
Request: Display Group Labels

### ISSUE THREAD

**Issue by axcrowe** [bitfocus/companion-module-etc-eos#47] opened 2024-05-02 16:40 UTC
Is there any possibility of adding a variable that displays an EOS group label? 

I would also be very interested in direct selects on the streamdeck, but started this new thread because I'd be happy with just the ability to see target labels as a work around.

Loving this module otherwise, thanks for creating and sharing it!

**Comment by n9yty** [comment] 2024-05-02 20:35
I picked up development of this after it was "abandoned" and brought it up to Companion 3.0 compatibility, but the bones and framework was created before I came along. I'm just trying to help out, as I don't even use it any longer since my involvement with the local High School stopped when they got their new console.

The problem is, unless you can see and duplicate EOS sending that data as OSC OUTPUT, there is no way to capture it. There is only minimal data that EOS sends as OSC by default and I don't think this is part of it.

I looked at direct selects briefly at one point but it doesn't seem that EOS is particularly interested in sending any of that data out. I toyed with setting up a Trigger in companion that set up a custom OSC flexi direct select group, but there was no way to really do much in the way of management and it created a lot of extra OSC traffic. I never got back to that as it seems setting up another display with Magic Sheets would be far more flexible than using a StreamDeck.

**Comment by n9yty** [comment] 2024-05-02 22:15
I'm not sure if this should be implemented or not, given how "chatty" it would make the OSC traffic.

I did find that I could subscribe to show update events using the /eos/subscribe=1 command.

It will then send out responses when show changes are made, for example if I label a group (although it doesn't get the initial value!)...

/eos/out/notify/group/list/0/2

I can then query to find out about the values on the group index 0:

/eos/get/group/index=0

And it responds:

/eos/out/get/group/1/list/0/3 0(i), UID(s), This is a test Label(s)
/eos/out/get/group/1/channels/list/0/2 0(i), UID(s), chanlist(s)

So there is hope there that there is technically "a way". However, how to know the bounds of how many or what indexes are going to be used? Variables have to be defined ahead of time, not dynamically, so it would create a LOT of placeholder variables to hold all permutations. Similar for Direct Selects I would imagine, the same issues apply, and "OSC Direct Selects" and banks are not the same as the physical ones or ones on a Magic Sheet/etc...

This seems like it would really need to be crafted to a particular implementation and would be hard to make generic.

**Comment by axcrowe** [comment] 2024-05-02 22:44
Yes! You're faster than me, I was working on a response pointing you towards that. That's good to know about the limitations, and we definitely don't want a ton of extraneous chatter. For my purposes, I'm looking to have 12 groups as my "hot swapping" ones, groups 1 thru 12.

I hear you about this being hard to make generic, but I think there's a real use case for this project in my industry. Folks are using all sorts of stuff to give the gaffer (head of the lighting dept) some limited control over fixtures.

**Comment by n9yty** [comment] 2024-05-03 00:32
Have a go with this version. It captures the labels for groups 1-20 on startup, subscribes to notifications, and if it sees a group updated (<= number 20) notification it tries to get the label and put it in a variable $(etc-eos:group_label_xx).  I made a button label using that variable and it indeed gets updated when I change the group label in EOS. VERY minimal testing at this point, but that is where you can help out. :)

Also, I think the other file I uploaded was not the correct version, I had changed my test/packaging and forgot about it so you got an old version. This incorporates all changes.

[companion-module-etc-eos.zip](https://github.com/bitfocus/companion-module-etc-eos/files/15195260/companion-module-etc-eos.zip)

**Comment by n9yty** [comment] 2024-05-03 00:59
@emichaelbaker I am afraid the same logic may not be applicable to Direct Selects becuase in OSC terms you have separate Direct Select banks/etc than what would be in a Magic Sheet or attached to the console, and so it is more than just getting a "number" and attaching the label to it.

Not writing it off entirely, but not part of this issue. There is still an open issue on Direct Select pages and it would be appropriate to address it there if it can be implemented.

**Comment by axcrowe** [comment] 2024-05-03 01:47
Thanks so much! I'll give this a go tomorrow and report back!

**Comment by n9yty** [comment] 2024-05-06 17:47
@axcrowe Just curious if you had a chance to test - I know life gets busy so no pressure. :)

**Comment by axcrowe** [comment] 2024-05-06 17:51
Hey, thanks for checking in. I’ve seen that the group labels work. I’ve just been trying to figure out how to load your custom code on my companionPi setup. I feel like I’m making progress, but it’s been a journey! If I can’t figure it out soon, I’ll let you know!

**Comment by n9yty** [comment] 2024-05-06 17:54
@axcrowe Just unpack the zip file and note where it is located. Then in the main companion GUI (not the web interface), click the GEAR icon in the upper right, it wille expose a "Developer modules path" field. Point that to the directory that you unpacked the files to. Not to the folder of this particular module but the directory it is inside of.

**Comment by axcrowe** [comment] 2024-05-06 17:59
So I got that to work for local control but couldn’t get that to work over
network to configure on the raspberry pi.

**Comment by n9yty** [comment] 2024-05-06 18:04
I know in the past I had set up VNC or other to remotely control a Pi's UI, but if you have it only in headless mode I don't know...

I found on my Mac under ~/Library/Application Support/companion a config.json file:

{
        "http_port": 8888,
        "bind_ip": "127.0.0.1",
        "start_minimised": false,
        "enable_developer": true,
        "dev_modules_path": "/Users/n9yty/Projects/companion/companion-module-dev"
}

Maybe you can find the equivalent on the Pi via SSH and set it up that way?

**Comment by n9yty** [comment] 2024-05-09 04:39
I'm going to close this as completed as my testing seems to have shown that it works and I'd like to get it pushed out.

**Closed by n9yty** 2024-05-09 04:39 UTC
